# Generated by Django 3.1.3 on 2022-06-21 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posturelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 18, 42, 17, 302318)),
        ),
    ]
