# Generated by Django 3.1.3 on 2022-08-11 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220621_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posturelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 19, 25, 42, 620454)),
        ),
    ]
