# Generated by Django 3.1.3 on 2022-06-20 23:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20220619_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posturelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 20, 23, 11, 24, 55057)),
        ),
    ]
