# Generated by Django 3.1.3 on 2022-08-11 19:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20220811_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posturelog',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 19, 25, 48, 200530)),
        ),
    ]
