# Generated by Django 3.1.3 on 2022-06-19 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='correction_video',
            fields=[
                ('video_index', models.AutoField(primary_key=True, serialize=False, verbose_name='게시글 인덱스')),
                ('posture', models.CharField(max_length=100, verbose_name='자세 이름')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('video_link', models.CharField(max_length=1000, verbose_name='영상 주소')),
            ],
            options={
                'db_table': 'correction_video',
            },
        ),
    ]
